minimum_single: 5
minimum_multiple: 5
disable_search_threshold: 0
minimum_width: 0
use_relative_width: false
jquery_selector: 'select:visible'
search_contains: true
disable_search: false
allow_single_deselect: true
placeholder_text_multiple: 'Choose options'
placeholder_text_single: 'Choose an option'
no_results_text: 'No matches'
max_shown_results: null
disabled_themes:
  bartik: '0'
  seven: '0'
chosen_include: 2
_core:
  default_config_hash: exRaKE0s6uZbfQrl_2WFEcTlc_1t81xEqCLuCCteUSk
