language: php
dist: trusty
sudo: false

php:
  - 7.3

env:
  global:
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
    - SYMFONY_DEPRECATIONS_HELPER="weak"

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini

before_script:
  # https://www.drupal.org/project/scheduler/issues/3179392#comment-13886570
  # At job start-up Composer is installed at 1.8.4 then self-update is run. From
  # 24 October 2020 this bumped the version to Composer 2. Drupal Core 8.8 has
  # plugins that only run with composer-plugin-api ^1.0 so revert to Composer 1.
  - travis_retry composer self-update --1;

script:
  - composer install
  - composer require drupal/entity_browser --dev # https://www.drupal.org/project/paragraphs/issues/2981850
  - cd web
  - ./../vendor/bin/drush site-install --existing-config --verbose --yes --db-url=sqlite://tmp/site.sqlite
  - ./../vendor/bin/drush runserver $SIMPLETEST_BASE_URL &
  - until curl -s $SIMPLETEST_BASE_URL; do sleep 1; done > /dev/null
  - ./../vendor/bin/phpunit -c core --group liiweb
