<?php

/**
 * @file
 * Contains liiweb_gazettes.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeManager;
use Drupal\node\Entity\Node;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_help().
 */
function liiweb_gazettes_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the liiweb_gazettes module.
    case 'help.page.liiweb_gazettes':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides custom functionality for Gzazettes') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function liiweb_gazettes_theme() {
  $theme = [];
  $path  = drupal_get_path('module', 'liiweb_gazettes') . '/templates';

  // table content field
  $theme['views_view'] = [
    'base hook' => 'views_view',
    'path'      => $path,
  ];
  return $theme;
}
