<?php

/**
 * @file
 * Contains liiweb_legislation.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Serialization\Json;
use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function liiweb_legislation_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the liiweb_legislation module.
    case 'help.page.liiweb_legislation':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide extra') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_views_pre_render().
 *
 * Creating menu list using JSON data
 *
 */

function liiweb_legislation_views_pre_render( $view)
{
  if ($view->id() == 'legislation') {

  }
}

/**
 * Implements hook_field().
 *
 * Creating menu list using JSON data
 *
 */
function liiweb_legislation_preprocess_field__node__field_toc__legislation(&$variables, $hook)
{

  $data = $variables['items']['0']['content']['#context']['value'];
  // dump($variables);
  $data = Json::decode($data);

  $items = [];
  $values = [];

  $variables['table_content'] = [
    '#theme'      => 'item_list__table_of_contents',
    '#type'       => 'ol',
    '#attributes' => [
      'class'     => ['toc-list menu-items'],
    ],
  ];

  foreach ($data as $key => $menu_item) {
    $items[] = liiweb_legislation_write_menu_item($menu_item);
  }

$variables['table_content']['#items'] = $items;
  // dump($variables['table_content']);

}


/**
 * Implements liiweb_legislation_write_menu_item().
 *
 * Creating list item with nested list item
 *
 * @param string $menu_item
 *
 */
function liiweb_legislation_write_menu_item($menu_item , $parent_id = Null)
{

  // $parent_id = $menu_item['id'];
  // exit;
//  dump($menu_item);
  try {
    $link = Link::fromTextAndUrl($menu_item['title'], Url::fromUri($menu_item['url'], [
      'attributes' => [
        'target' => '_blank',
        'class'  => ['link-item'],
      ]
    ]));

    $item = [
      '#markup' => '<a href="#'  . $menu_item['id'] . '" class="link-item" >' . $menu_item['title'] . '</a>',
      '#wrapper_attributes' => [
        'class'             => ['toc-item-' . $menu_item['type']],
      ],
    ];

  } catch (Exception $e) {
    // Generic exception handling if something else gets thrown.
    \Drupal::logger($item)->error($e->getMessage());
  }

  // check if list has children
  if (isset($menu_item['children'])) {
    $items = [];
    $menu  = [
      '#theme'      => 'item_list__table_of_contents__child',
      '#type'       => 'ul',
      '#attributes' => [
        'class'     => ['menu-items has-children'],
      ],
    ];


    $parent_id = $menu_item['component'];
    //loop through children and return item_list
    foreach ($menu_item['children'] as $key => $menu_item) {
      // dump($menu_item);

      $items[] = liiweb_legislation_write_menu_item($menu_item, $parent_id . '/');

      // if ($menu_item['children']) {
      // }
    }
    $menu['#items'] = $items;
    $item['menu_items'] = $menu;
  }
  // dump($value);

  return $item;
}

/**
 * Implements hook_theme().
 */
function liiweb_legislation_theme() {
  $theme = [];
  $path  = drupal_get_path('module', 'liiweb_legislation') . '/templates';

  // table content field
  $theme['field__node__field_toc__legislation'] = [
    'base hook' => 'field',
    'path'      => $path,
  ];

  // view custom block tab

  $theme['view_tabs_block'] = [
    'template'  => 'view-tabs-block',
    'path'      => $path,
    'variables' => [
      'subject' => Null,
      'search'  => Null,
      'browser' => Null,
      'glossary_filter' => Null,
    ],
  ];

  $theme['lifecycle_timeline'] = [
    'template'  => 'lifecycle-timeline',
    'path'      => $path,
  ];

  return $theme;
}

/**
 * Implements hook_ENTITY_view().
 */
function liiweb_legislation_node_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if($entity->getType() == 'legislation' && $view_mode == 'full') {  

    $raw_json = json_decode($build['#node']->get('field_raw_json')->getValue()[0]['value']);
    $build['#attached']['drupalSettings']['liiweb_legislation']['raw_json'] = $raw_json;

    $repeal = $build['#node']->get('field_repeal');
    if($repeal->getValue()) {
      $paragraph = \Drupal\paragraphs\Entity\Paragraph::load($repeal->getValue()[0]['target_id']);
      $date = $paragraph->get('field_repeal_date')->getValue()[0]['value'];

      $repeal_id = $paragraph->get('field_repeal_work')->getValue()[0]['target_id'];
      if ($repeal_entity = \Drupal::entityTypeManager()->getStorage('node')->load($repeal_id)) {
        $repeal_name = $repeal_entity->getTitle();
        $link_to_repeal = $repeal_entity->toUrl();
      }

      $build['field_frbr_uri']['#attributes']['class'][] = 'alert-red';
      $build['field_frbr_uri'][0]['#template'] = '{{ value|raw }}';
      $build['field_frbr_uri'][0]['#context']['value'] = "This legislation was repealed on $date by <h3 class='h6'><a href='$link_to_repeal'>$repeal_name.</a></h3>";
    }
    elseif($build['#node']->isDefaultRevision()) {
      $build['field_frbr_uri']['#attributes']['class'][] = 'alert-primary';
      $build['field_frbr_uri'][0]['#context']['value'] = 'This is the latest version of this legislation.';
    }
    else {
      //WORK IN FORCE FIELDS TO BE UPDATED
      $work_in_force_from = $raw_json->commencement_date;
      $work_in_force_to = $raw_json->commencement_date;
      $link_to_current_revision = $entity->toUrl()->toString();

      $build['field_frbr_uri']['#attributes']['class'][] = 'alert-red';
      $build['field_frbr_uri'][0]['#template'] = '{{ value|raw }}';
      $build['field_frbr_uri'][0]['#context']['value'] = "This is the version of this legislation as it was from $work_in_force_from to $work_in_force_to. <h3 class='h6'><a href='$link_to_current_revision'>Read the version currently in force.</a></h3>";
    }
  }
}


