<?php

/**
 * @file
 * Contains liiweb_judgment.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_help().
 */
function liiweb_judgment_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the liiweb_judgment module.
    case 'help.page.liiweb_judgment':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides custom functionality for judgment') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function liiweb_judgment_theme() {
  $theme = [];
  $path = drupal_get_path('module', 'liiweb_judgment') . '/templates';
  // view custom block tab

  $theme['view_tabs_block'] = [
    'template' => 'view-tabs-block',
    'path' => $path,
    'variables' => [
      'subject' => NULL,
      'search' => NULL,
      'browser' => NULL,
      'glossary_filter' => NULL,
    ],
  ];
  return $theme;
}

function liiweb_judgment_node_presave(Drupal\node\NodeInterface $node) {
  if ($node->getType() == 'judgment') {
    $matter_type = $node->get('field_matter_type')->getValue();
    $number_numeric = $node->get('field_case_number_numeric')->getValue();
    $number_year = $node->get('field_case_number_year')->getValue();
    $val_arr = [];
    $matter = [];
    foreach ($matter_type as $key => $mitem) {
      $term = Term::load($mitem['target_id']);
      $name = $term->get('name')->getValue()[0]['value'];
      $matter[] = $name;
    }
    foreach($number_numeric as $key => $nitem){
    $num = $key + 1;
    if(!empty($matter[$key])){
    $val_arr[] = $matter[$key] . " " . $number_numeric[$key]['value'] . ' of ' . $number_year[$key]['value'];
    }
    else{
    $val_arr[] =$number_numeric[$key]['value'] . ' of ' . $number_year[$key]['value'];
    }
    }
    $node->set('field_case_number', $val_arr);
  };
}

/**
 * Implements hook_form_alter().
 */
function liiweb_judgment_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['#validate'][] = 'numFieldsValidation';

//  $form['field_case_number']['#access'] = FALSE;
}

function numFieldsValidation(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  if (isset($form_state->getUserInput()['field_case_number_numeric']) && isset($form_state->getUserInput()['field_case_number_year'])) {
    $num = [];
    foreach ($form_state->getUserInput()['field_case_number_numeric'] as $num_item) {
      if(!empty($num_item['value'])) {
        $num[] = $num_item['value'];
      }
    }
    $count_numeric = count($num);
    $year = [];
    foreach ($form_state->getUserInput()['field_case_number_year'] as $year_item) {
      if(!empty($year_item['value'])) {
        $year[] = $year_item['value'];
      }
    }
    $count_year = count($year);
    if ($count_year != $count_numeric) {
      $form_state->setError($form['field_case_number_numeric'], "Please, fill equal counts for Matter type, Case Numeric and Case Year fields");
    }
  }

}
