<?php

use Drupal\node\NodeInterface;
use Drupal\Core\Language\LanguageInterface;
use Drupal\liiweb\Plugin\LanguageNegotiation\LanguageNegotiationFrbrUri;
use Drupal\language\Plugin\LanguageNegotiation\LanguageNegotiationUrlFallback;

/**
 * Implements hook_node_presave().
 */
function liiweb_node_presave(NodeInterface $node) {
  if ($node->isDefaultRevision() && !empty($node->field_frbr_uri->value)) {
    /** @var \Drupal\Core\Path\AliasStorageInterface $pathService */
    $pathService = \Drupal::service('path.alias_storage');
    $pathService->delete([
      'source' => '/node/' . $node->id(),
      'langcode' => $node->language()->getId(),
    ]);

    $node->path = [
      'alias' => $node->field_frbr_uri->value,
      'pathauto' => 0,
    ];
  }
}

/**
 * Implements hook_language_types_info_alter().
 */
function liiweb_language_types_info_alter(array &$language_types) {
  $language_types[LanguageInterface::TYPE_URL]['fixed'] = [LanguageNegotiationFrbrUri::METHOD_ID, LanguageNegotiationUrlFallback::METHOD_ID];
}


/**
 * Implements hook_entity_type_alter().
 */
function liiweb_entity_type_alter(array &$entity_types) {
  $entity_types['node']->addConstraint('UniqueURI', []);
}
