<?php

use Drupal\Core\Language\LanguageInterface;
use Drupal\liiweb\Plugin\LanguageNegotiation\LanguageNegotiationFrbrUri;
use Drupal\language\Plugin\LanguageNegotiation\LanguageNegotiationUrlFallback;

/**
 * Implements hook_theme().
 */
function liiweb_theme($existing, $type, $theme, $path) {

  $theme = [];
  $path = drupal_get_path('module', 'liiweb') . '/templates';

  $theme['text_block'] = [
    'variables' => [
      'title' => Null,
      'text' => Null,
    ],
  ];

  $theme['country_block'] = [
    'variables' => [
      'content' => Null,
    ],
  ];

  $theme['liiweb_file']  = [
      'variables' => [
        'files' => NULL,
      ],
    'template' => 'liiweb-file',
  ];


  $theme['social_news_timeline'] = [
    'template'            => 'social-news-timeline',
    'variables'           => [
      'facebook_page_url' => NULL,
      'facebook_app_id'   => NULL,

      'twitter_handle'    => NULL,
    ],
    'path'                => $path,
  ];

  $theme['liiweb_contact'] = [
    'template'       => 'liiweb-contact',
    'path'           => $path,
    'variables'      => [
      'intro'        => NULL,
      'contact_entities' => [],
    ],
  ];

  return $theme;
}

/**
 * Implements hook_language_types_info_alter().
 */
function liiweb_language_types_info_alter(array &$language_types) {
  $language_types[LanguageInterface::TYPE_URL]['fixed'] = [LanguageNegotiationFrbrUri::METHOD_ID, LanguageNegotiationUrlFallback::METHOD_ID];
}

/**
 * Implements hook_entity_type_alter().
 */
function liiweb_entity_type_alter(array &$entity_types) {
  $entity_types['node']->addConstraint('UniqueURI', []);
}
