<?php

/**
 * @file
 * Contains liiweb_judgement.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function liiweb_judgement_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the liiweb_judgement module.
    case 'help.page.liiweb_judgement':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides custom functionality for judgement') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function liiweb_judgement_theme() {
  $theme = [];
  $path  = drupal_get_path('module', 'liiweb_judgement') . '/templates';
  // view custom block tab

  $theme['view_tabs_block'] = [
    'template'  => 'view-tabs-block',
    'path'      => $path,
    'variables' => [
      'subject' => Null,
      'search'  => Null,
      'browser' => Null,
      'glossary_filter' => Null,
    ],
  ];
  return $theme;
}
